llm:
  api_type: "dashscope"
  model: "deepseek-r1-distill-qwen-32b"
  base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
  api_key: "sk-342db74ded07471fb003961e87edfea5"

models:
  qwen-plus:
    model: "qwen-plus"
    api_key: "sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"

  deepseek-r1:
    api_type: "dashscope"
    api_key: "sk-342db74ded07471fb003961e87edfea5"
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"

  "deepseek-ai/DeepSeek-R1-Distill-Qwen-32B": # api_type: "openai"  # or azure / ollama / groq etc.
    api_type: "siliconflow"  # or azure / ollama / groq etc.
    base_url: "https://api.siliconflow.cn/v1/chat/completions"
    api_key: "Bearer sk-znyqmmbjhfshaxknzxkzlpgirwxdwhvnjqjapzuukuagjvmz"

  "gpt-4o-mini": # api_type: "openai"  # or azure / ollama / groq etc.
    api_type: "openai"  # or azure / ollama / groq etc.
    base_url: "<your base url>"
    api_key: "<your api key>"

  "deepseek-r1-distill-qwen-32b": # api_type: "openai"  # or azure / ollama / groq etc.
    api_type: "dashscope"  # or azure / ollama / groq etc.
    base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
    api_key: "sk-342db74ded07471fb003961e87edfea5"
